version: '3'
services:
  app-admin:
    container_name: gpw-app-admin
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./config/secure/docker.env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_TEMP_DIR: /app-data
      spring_profiles_active: prod
    networks:
      - gpw-network
    volumes:
      - ./.docker-volumes/app-data:/app-data
      - ./admin-github-release.jar:/app-build/admin-prod.jar
    entrypoint: java -jar /app-build/admin-prod.jar --server.port=8081


networks:
  gpw-network:
    external: true