version: '3'
services:
  app-restapi:
    container_name: gpw-app-restapi
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_TEMP_DIR: /app-data
      spring_profiles_active: prod
    networks:
      - gpw-network
    volumes:
      - ./.docker-volumes/app-data:/app-data
      - ./restapi-github-release.jar:/app-build/restapi-prod.jar
    entrypoint: java -jar /app-build/restapi-prod.jar --server.port=8080

networks:
  gpw-network:
    external: true