version: '3'
services:
  app-admin:
    container_name: gpw-app-admin
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "80"
      - "443"
    environment:
      TZ: Europe/Warsaw
      VIRTUAL_HOST: www.gpwadmin.g-sitemap-generator.com,gpwadmin.g-sitemap-generator.com
      VIRTUAL_HOST_ALIAS: gpwadmin.g-sitemap-generator.com
      LETSENCRYPT_HOST: gpwadmin.g-sitemap-generator.com,www.gpwadmin.g-sitemap-generator.com
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_TEMP_DIR: /app-data
      spring_profiles_active: prod
    networks:
      - gpw-network
      - my-network
    volumes:
      - ./.docker-volumes/app-data:/app-data
    entrypoint: java -jar /app-build/admin/target/app-admin.jar --server.port=80

networks:
  gpw-network:
    external: true
  my-network:
    external: true # this network should exist in nginx-proxy docker-compose.yml