spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC
  config:
    import:
      - classpath:dataprovider.yml
      - classpath:config/datacenter-redis.yml
      - classpath:config/datacenter-db.yml
      - classpath:config/logger.yml

logging:
  level:
    root: WARN # all logs e.g. then WARN
    pl.slaszu.gpw: DEBUG # pl.slaszu.gpw app logs e.g. then DEBUG

