server:
  port : 8081

spring:
  security:
    oauth2:
      client:
        registration:

          google:
            clientId: ${google.clientId}
            clientSecret: ${google.clientSecure}

          github:
            clientId: ${dev.github.clientId}
            clientSecret: ${dev.github.clientSecret}
            scope:
              - user:email

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC

  config:
    import:
      - classpath:config/datacenter-redis.yml
      - classpath:config/datacenter-db.yml
      - classpath:config/logger.yml
      - test.yml
      - dataprovider.yml
      - classpath:config/secure/oauth-credentials.yml
