server:
  port : 8081

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: e15011ab38988136b693
            clientSecret: 9e73b084d886620ee8bec58593bd1a782aa70429
            scope:
              - user:email

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC

  config:
    import:
      - classpath:config/datacenter-redis.yml
      - classpath:config/datacenter-db.yml
      - classpath:config/logger.yml
      - test.yml
