spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: e15011ab38988136b693
            clientSecret: 9e73b084d886620ee8bec58593bd1a782aa70429
            scope:
              - user:email

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3309}/gpw-db
    username: gpw
    password: gpw-password-213!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC