spring:
  security:
    oauth2:
      client:
        registration:

          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}

          github:
            clientId: ${GITHUB_CLIENT_ID_PROD}
            clientSecret: ${GITHUB_CLIENT_SECRET_PROD}
            scope:
              - user:email