server:
  port : 8081

spring:
  security:
    oauth2:
      client:
        registration:

          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}

          github:
            clientId: ${GITHUB_CLIENT_ID_DEV}
            clientSecret: ${GITHUB_CLIENT_SECRET_DEV}
            scope:
              - user:email

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC

  config:
    import:
      - classpath:config/datacenter-redis.yml
      - classpath:config/datacenter-db.yml
      - classpath:config/logger.yml
      - test.yml
      - dataprovider.yml
